06 02 AppInput -in progress
js-tasks-ru/vue-20210119_istomina-asia pull request #10
Opened 2021-02-14 08:26 UTC by ase444ka

2021-02-26 22:16 UTC, ShGKme requested changes
Требуется изменить работу с состоянием в `ImageUploader`

2021-02-26 22:16 UTC, ShGKme commented on 06-deep-vue/04-ImageUploader/components/ImageUploader.vue
> +import { ImageService } from '../image-service.js';
`.js` был нужен нам только, когда мы работали с нативными модулями, где требовалось указывать полный путь до файла. При сборке приложения для зарегистрированных типов модулей можно не указывать расширение.

2021-02-26 22:16 UTC, ShGKme commented on 06-deep-vue/04-ImageUploader/components/ImageUploader.vue
> +    },
В общем случае определять `status` только по изменению `imageId` нельзя. 
Например, в случае ошибки загрузки изображения `imageId` не изменится, но статус всё равно изменится с загрузки на прошлое состояние.

2021-02-26 22:16 UTC, ShGKme commented on 06-deep-vue/04-ImageUploader/components/ImageUploader.vue
> +      status: 'empty',
Если компонент инициализируется с уже выбранным изображением, то `status` должен быть другой.

2021-02-26 22:16 UTC, ShGKme commented on 06-deep-vue/04-ImageUploader/components/ImageUploader.vue
> +      setTimeout(() => (this.justDeleted = false), 50);
Что делает этот код?

2021-02-26 22:16 UTC, ShGKme commented on 06-deep-vue/03-DateInput/components/DateInput.vue
> +  console.log(step);
Лучше убрать отладочный вывод.

2021-02-28 09:28 UTC, ase444ka commented on 06-deep-vue/04-ImageUploader/components/ImageUploader.vue
> +      setTimeout(() => (this.justDeleted = false), 50);
Предотвращает загрузку картинки. Если его убрать, клик, удаляющий картинку, обрабатывается на инпуте (который уже не disabled, т.к. статус empty) и снова открывается окно выбора файла.

2021-02-28 20:30 UTC, ShGKme approved these changes
Все задачи приняты

2021-02-28 20:31 UTC, merged